### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by spotshare-nick** [beerjs/pdx#2]
Looking for a BeerJS in Portland if one is available...

**Comment by jordanpapaleo** [comment]
Hi.  So I am not involved with Portland so I can t answer this question for you.  If no one speaks up, would you be interested in running a few PDX beers events?

**Comment by spotshare-nick** [comment]
Hi Jordan. Hope Reno is treating you well still.  As I just arrived in Portland, I likely need to get a lay of the land first.  Seems Portland has other beer + programming events (more like /dev/Reno than the old BeerJS Tahoe).  So the quick answer is that I'll get back to you on Slack/SMS if I decide there's a group here anywhere near as special as the Tahoe group (miss you guys!) that needs a BeerJS as opposed to the existing groups.

**Comment by jordanpapaleo** [comment]
You never said goodbye!  But at least I know why you have not been to our reno event :)

**Comment by michaelhalstead** [comment]
Hey! We’d love to have you at BeerJS PDX. I’m working to set the date for this months meeting, but if you join our MeetUp group, you’ll see when we create the event!


Check out bridgetown dev http://meetu.ps/c/4kBjd/Cn5lK/a on Meetup http://meetu.ps/c/4kBjd/Cn5lK/a

Looking forward to meeting you!

________________________________
